spring:
  application:
    name: BlogMs
  config:
    import: consul://localhost:8500/BlogMs/application # Specifies that configuration should be loaded from Consul
  cloud:
    consul:
      discovery:
        hostname: host.docker.internal
      config:
        enabled: true  # Enable Consul configuration management